
test:test2.cpp  ../Server.cpp  ../EventLoopThreadPool.cpp  ../EventLoopThread.cpp  ../Epoller.cpp  ../Channel.cpp ../HttpService.cpp ../base/Logging.cpp  ../base/LogStream.cpp ../EventLoop.cpp ../base/AsyncLogging.cpp  ../base/Thread.cpp ../base/LogFile.cpp ../Timer.cpp  ../base/CountDownLatch.cpp  ../base/Condition.cpp
	g++ test2.cpp  ../Server.cpp  ../EventLoopThreadPool.cpp  ../EventLoopThread.cpp   ../Epoller.cpp   ../Channel.cpp  ../HttpService.cpp  ../EventLoop.cpp ../Util.cpp  ../base/Logging.cpp  ../base/LogStream.cpp ../base/AsyncLogging.cpp  ../base/Thread.cpp ../base/FileUtil.cpp ../base/LogFile.cpp ../Timer.cpp   ../base/CountDownLatch.cpp  ../base/Condition.cpp   -std=c++11  -lpthread -o test
#test2.o:test2.cpp Thread.o EventLoop.o
#	 g++ test2.cpp Thread.o EventLoop.o -o test2.o -lpthread
#EventLoop.o:../EventLoop.cpp
#	g++ ../EventLoop.cpp -o EventLoop.o
#Thread.o:../base/Thread.cpp
#	g++ ../base/Thread.cpp -o Thread.o


	

